# All the Relational or Comparision Operators
a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))
c=(a<b)
d=(a>b)
e=(a>=b)
f=(a<=b)
g=(a!=b)
h=(a==b)
print("Boolean Value is : ",c)
print("Boolean Value is : ",d)
print("Boolean Value is : ",e)
print("Boolean Value is : ",f)
print("Boolean Value is : ",g)
print("Boolean Value is : ",h)
